---
- hosts: all
  gather_facts: no
  become: yes

  tasks:
    # does the majority of the cleanup:
    - name: uninstall k3s
      command: /usr/local/bin/k3s-uninstall.sh
      ignore_errors: yes

    # far more reliable than the docker_host_info/docker_containers method:
    - name: stop/rm all containers
      shell: docker stop $(docker ps -q); docker rm $(docker ps -qa);
      ignore_errors: yes

    # slower than command, but more appropriate for ansible:
    - name: delete all data
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/rancher
        - /etc/ssl/etcd
        - /etc/logrotate.d/k3s
        - /var/lib/rancher
        - /var/lib/etcd
        - /var/log/k3s.log
        - /var/log/pods
        - /var/log/containers

    # tends to leave orphaned containers:
    # - name: get all container info
    #   docker_host_info:
    #     containers: yes
    #     networks: no
    #     images: no
    #     disk_usage: no
    #     volumes: no
    #   register: containers

    # - name: remove all running containers
    #   docker_container:
    #     name: "{{ item.Names[0] | regex_replace('^/', '') }}"
    #     state: absent
    #   loop: "{{ containers.containers }}"
