---
- hosts: all
  gather_facts: no
  become: yes

  tasks:
    # does the majority of the cleanup:
    - name: uninstall k3s
      command: /usr/local/bin/k3s-uninstall.sh
      ignore_errors: yes

    - name: uninstall k3s-agent
      command: /usr/local/bin/k3s-agent-uninstall.sh
      ignore_errors: yes

    # slower than command, but more appropriate for ansible:
    - name: delete all data
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/rancher
        - /var/lib/rancher
        - /var/log/pods
        - /var/log/containers

    - command: journalctl --rotate
      when: clean_journalctl | bool
    - command: journalctl --vacuum-time=1s
      when: clean_journalctl | bool
    - command: journalctl --vacuum-time=0s
      when: clean_journalctl | bool

    - reboot:
