---
- name: set permissions
  file:
    path: /etc/ssl/etcd
    owner: root
    group: root
    mode: "0700"

- name: create etcd bin directory
  file:
    path: "{{ etcd_data_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0755"

- include_tasks: "packages.yml"

- name: generate etcd cluster token
  command: apg -n 1 -m 63 -x 63 -M LNC -a 1
  register: etcd_cluster_token
  delegate_to: localhost
  run_once: yes

- include_tasks: docker.yml

# used to set 'etcd_initial_cluster_state: existing' after first startup
- include_tasks: docker.yml
