---
- name: install apg
  package:
    name: apg
    state: present
    use: "{{ ansible_pkg_mgr }}"
  delegate_to: localhost
  run_once: yes

- name: install python docker support
  pip:
    name: docker
    state: latest
