---
- name: Gather facts
  setup:
  tags:
    - ha
    - workers

- name: download k3s setup script
  get_url:
    url: https://get.k3s.io
    dest: /tmp/k3s.sh
    mode: "0755"
  tags:
    - ha
    - managers
    - workers

- name: check if k3s config directory already exists
  stat:
    path: /etc/rancher/k3s
  register: etck3s
  tags:
    - ha
    - workers

- name: setup k3s
  command: |
    /tmp/k3s.sh \
    --docker
  environment:
    - "{{ k3s_config.common }}"
    - "{{ k3s_config.managers }}"
  when: not etck3s.stat.exists
  delegate_to: "{{ groups['k3s_managers'][0] }}"
  run_once: yes

- name: setup k3s (managers)
  command: |
    /tmp/k3s.sh \
    --docker
  environment:
    - "{{ k3s_config.common }}"
    - "{{ k3s_config.managers }}"
  when: inventory_hostname != groups['k3s_managers'][0] and not etck3s.stat.exists
  tags:
    - ha

- name: wait for token file to populate
  wait_for:
    path: /var/lib/rancher/k3s/server/token
  delegate_to: "{{ groups['k3s_managers'][0] }}"
  run_once: yes
  tags:
    - workers

- name: get join token
  slurp:
    src: /var/lib/rancher/k3s/server/token
  register: k3s_cluster_token
  delegate_to: "{{ groups['k3s_managers'][0] }}"
  run_once: yes
  tags:
    - workers

- name: setup k3s (workers)
  command: |
    /tmp/k3s.sh \
    --docker
  environment:
    - "{{ k3s_config.common }}"
    - "{{ k3s_config.workers }}"
    - K3S_TOKEN: "{{ k3s_cluster_token.content | b64decode | trim }}"
  when: inventory_hostname in groups['k3s_workers'] and not etck3s.stat.exists
  tags:
    - workers
