---
- name: ensure docker engine is installed
  apk:
    name: docker
    state: present
    update_cache: yes

- name: start & enable docker service
  service:
    name: docker
    state: started
    enabled: yes
