query_nodes: "[].{name: metadata.name, ready: status.conditions[?type == 'Ready'].status | [0], labels: metadata.labels, master: metadata.labels.\"node-role.kubernetes.io/master\"}"
k3s_config:
  common:
    # INSTALL_K3S_VERSION:
    INSTALL_K3S_CHANNEL: latest
  managers: {}
  workers: {}
